### ISSUE TITLE
Creating (and using) subdomains

### ISSUE THREAD

**Issue by commadelimited** [GearHost/docs#2]
The "Creating a subdomain article, while technically correct, does not offer insight on how to access the subdomain once it has been created.

https://github.com/GearHost/docs/blob/master/docs/how-to-add-a-domain-subdomain-hostname.md

It would be nice if it could at least link to other articles on how to access the subdomain, or direct content to be viewed only through there.

**Comment by ryankekos** [comment]
I see what you mean. I've updated the article. Let me know your thoughts. Thanks.

**Comment by ryankekos** [comment]
I didn't hear back Andy so I'm going to close this. Hopefully the update is better. Thanks!
