### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by stephl1234** [GearHost/Docs#6]
Help! My company's website has been down all day and I can't get ahold of anyone to see what the status of getting it up is. Hopefully this can get fixed asap! Website: www.citcfx.com

Thanks,
Stephanie Long

**Comment by ryankekos** [comment]
We apologize for the issue Stephanie however this support area is for our software, not support in general so I'll delete this however this was quickly resolved when it first happened. Again our apologies and let us know if you need anything further,
